### ISSUE TITLE
Not an issue. Need permission from you

### ISSUE THREAD

**Issue by mohsinbaber** [lwhite14/StaticMist#16]
Hi Luke. Hope you are fine.
Can you kindly allow me to use this project for my personal use? I want to upload this game on play store. I will definitely give you due credit.

**Comment by lwhite14** [comment]
Hey Muhammad, I appreciate the request however I don't want the game on the Play Store. Feel free to download the source code to inspect and change for your own personal improvement, but the game has already been released on itch.io and that is the only platform I wish to release it on. 
Thanks!
